routes/web.php
<?php

Route::get('/painel/produtos/tests','Painel\ProdutoController@tests'); 
Route::resource('painel/produtos', 'Painel\ProdutoController');
Route::resource('painel/clientes', 'Painel\ClienteController'); 
Route::resource('painel/pedidos', 'Painel\PedidoController');
Route::resource('painel/carrinho', 'Painel\CarrinhoController');

Route::get('/carrinhos/{id}', 'Painel\CarrinhoController@create');



Route::get('/carrinho/{id}', 'Painel\CarrinhoController@index');
Route::get('/carrinho_create/{id}', 'Painel\CarrinhoController@create');
Route::get('/teste/{id}', 'Painel\CarrinhoController@create');

#Route::get('/item/{id}', 'Painel\CarrinhoController@index');



Route::group(['namespace' => 'Site'], function() {#Caminho Site\SiteController #Grupo presente no mesmo namespcace

    Route::get('/categoria/{id}', 'SiteController@categoria');
    Route::get('/categoria2/{id?}', 'SiteController@categoriaOp');
    


    Route::get('/contato','SiteController@contato');
   

});

Route::get('/','HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'HomeController@index')->name('home');

app/Models/Painel/Carrinho.php
<?php

namespace App\Models\Painel;

use Illuminate\Database\Eloquent\Model;

class Carrinho extends Model
{

    protected $fillable = ['produto_id','pedido_id','produto','quantidade','sub_total'];

    public function product()
    {
        return $this->belongsTo(Product::class,'produto_id');
    }

    public function pedido()
    {
        return $this->belongsTo(Pedido::class,'pedido_id');
    }
}

app/Models/Painel/Cliente.php
<?php

namespace App\Models\Painel;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $fillable = ['name','email','senha']; 

    Public function pedido(){
        
        return $this->hasone(Pedido::class);
       }
   
}

app/Models/Painel/Pedido.php
<?php

namespace App\Models\Painel;

use Illuminate\Database\Eloquent\Model;

class Pedido extends Model
{
    protected $fillable = ['quantidade','total','cliente_id','preco','carrinho_id'];
    
    public function cliente()
    {
        return $this->belongsTo(Cliente::class,'cliente_id');
    }


    public function carrinho()
    {
        return $this->hasMany(Carrinho::class,'carrinho_id');
    }


    
}

app/Http/Controllers/Painel/CarrinhoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Painel\Carrinho;
use App\Models\Painel\Product;
use App\Models\Painel\Pedido;

class CarrinhoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $carrinho;
    private $totalPage = 10;

    public function __construct(Carrinho $carrinho)
    {
        $this->carrinho = $carrinho;
    }

    public function index($idPedido)
    {
        dd($idPedido);
        $title = 'Listagem pedidos';
        $carrinhos = $this->carrinho->with('product')->paginate($this->totalPage);
        return view('painel.carrinhos.index',compact('carrinhos','title','idPedido')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {   
        
        $pedidoId = $id;

        $plucked = product::pluck('name','id','preco');

        return view('painel.carrinhos.create-edit',compact('pedidoId','plucked'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request ,Product $requestss)
    {

        $dataForm = $request->all();
        
        dd($dataForm);

        $idProduto = $dataForm['produto_id'];

        $buscaProduto = $requestss->find($idProduto);

        $buscaPreco = $buscaProduto['preco']; //busca o preco setado no produto selecionado

        $subTotal = $buscaPreco * $dataForm['produto_qtde'];

        $dataForm['sub_total'] = $subTotal;

        $buscaNome = $buscaProduto['name'];

        $dataForm['produto'] = $buscaNome;

        $insert = $this->carrinho->create($dataForm); //Faz cadastro
        
        $idCarrinho = $insert['id'];

        $pedido_id = Carrinho::find($idCarrinho)->only('pedido_id');
                
        $carrinhos = carrinho::where('pedido_id',$pedido_id)->get();

        if($insert)
        {
            return view('painel.pedidos.show',compact('carrinhos'));
        }
        else 
            return redirect()->route('carrinho.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $pedido_id = Carrinho::find($id)->only('pedido_id');

        $teste = Carrinho::find($id);
        
        $delete =  $teste->delete();
        
        $carrinhos = carrinho::where('pedido_id',$pedido_id)->get();
        
        
            if($delete)
                {
                     return view('painel.pedidos.show', compact('carrinhos'));
                }
                     else return redirect()->route('carrinho.show', $id)->with(['errors'=>'Falha ao deletar']);
    }
}

app/Http/Controllers/Painel/ClienteController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Painel\Cliente;
use App\Http\Requests\Painel\ClienteFormRequest;


class ClienteController extends Controller
{

    private $cliente;
    private $totalPage = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct(Cliente $cliente)
     {
         $this->cliente = $cliente;
     }

    public function index()
    {   
        $title = 'Listagem produtos';
        $clientes = $this->cliente->paginate($this->totalPage);
        return view('Painel.clientes.index',compact('clientes','title'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('painel.clientes.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClienteFormRequest $request)
    {
        $dataForm = $request->all();
       
        $insert = $this->cliente->create($dataForm); //Faz cadastro

        if($insert)
        {
            return redirect()->route('clientes.index'); 
        }
        else 
            return redirect()->route('clientes.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
                $cliente = $this->cliente->find($id);
        
                $title = "Produto: $cliente->name";
        
                return view('painel.clientes.show',compact('cliente','title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
                $cliente = $this->cliente->find($id); //recuperando produto pelo id
        
                $title = "Editar Cliente: $cliente->name";
                        
                return view('painel.clientes.create-edit', compact('title','cliente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dataForm = $request->all();
        
                //recupera o item pelo id
                $cliente = $this->cliente->find($id);
        
                //altera os itens
                $update = $cliente->update($dataForm);
        
                    //verifica se foi alterado
                    if($update)
                    {
                        return redirect()->route('clientes.index');
                    }
                    else 
                        return redirect()->route('clientes.edit',$id)->with(['errors'=>'Falha ao editar']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            $cliente = $this->cliente->find($id);
        
            $delete =  $cliente->delete();
        
            if($delete)
            {
                 return redirect()->route('clientes.index');
            }
                 else return redirect()->route('clientes.show', $id)->with(['errors'=>'Falha ao deletar']);
    }
}

app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PainelController extends Controller
{
    
}

app/Http/Controllers/Painel/PedidoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Painel\Pedido;
use App\Models\Painel\Cliente;
use App\Models\Painel\Product;
use App\Models\Painel\Carrinho;
use App\Http\Requests\Painel\PedidoFormRequest;
use App\Http\Requests\Painel\ProductFormRequest;


class PedidoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $pedido;
    
    
    private $totalPage = 10;

    public function __construct(Pedido $pedido)
    {
        
        $this->pedido = $pedido;
        
    
    }

    public function index()
    {
        $title = 'Listagem pedidos';
        $pedidos = $this->pedido->with('cliente')->paginate($this->totalPage);
        
        return view('Painel.pedidos.index',compact('pedidos','title'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Cadastro';

        $plucked = cliente::pluck('name','id');

        $produtos = product::pluck('name','id','preco'); 
        
        /*dd($plucked->all());
        $plucked1->all();*/
        
        return view('painel.pedidos.create-edit',compact('title','plucked','produtos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PedidoFormRequest $request)
    {
        $dataForm = $request->all();   
        
        //dd($dataForm);

        $produto_id = $dataForm['produto_id']; //ids dos produtos 

        /*$pd_id = (int)$produto_id;
        $teste = product::where('id', $pd_id)->get();

        dd($teste);*/
         
        $insert = $this->pedido->create($dataForm); //Faz cadastro

        $pedido_id = $insert->id;
        
        
        $quantidade = $dataForm['Quantidade'];
        $sub_Total = $dataForm['SubTotal'];

        //$pl=['produto_id' => $teste, 'pedido_id' => '1' , 'produto' => 'teste', 'quantidade' => '1','sub_total' => '1'];
        

    

        $contador = count(request('produto_id'));
        $produto_id = request('produto_id');
        $quantidade = request('Quantidade');
        $sub_total = request('SubTotal');
        $pedido_id = $insert->id;
        

        for($x=0; $x<$contador; $x++){
        $data[] = [
            'produto_id' => (int)$produto_id[$x],
            'pedido_id' => $pedido_id,
            'quantidade' => $quantidade[$x],
            'sub_total' => $sub_total[$x]        
        ];
        carrinho::create($data[$x]);
    } 


          
      
        //dd($insert->id); //id do pedido

        if($insert)
        {           
          
            return redirect()->route('pedidos.index'); 
        }   
        
        else 
            return redirect()->route('pedidos.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
                $pedido = $this->pedido->find($id);
                $carrinhos = carrinho::where('pedido_id' , $id)->get();
                $total =$carrinhos->sum('sub_total');
                
               # $title = "Pedido: $pedido->name";
        
                return view('painel.pedidos.show',compact('pedido','carrinhos','total'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $pedido = $this->pedido->find($id); //recuperando produto pelo id

        return view('painel.pedidos.create-edit', compact('pedido'));
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $requests , $id)
    {
         //editar item

        //Recupera todos os itens
                $dataForm = $request->all();
        
                //recupera o item pelo id
                $pedido = $this->pedido->find($id);

                $idProduto = $dataForm['produto_id']; //Capturando o id do produto cadastrado
                
                $buscaId = $requests->find($idProduto); //buca o produto pelo id
                
                $buscaPreco = $buscaId['preco']; //busca o preço setado no produto selecionado
                        
                $dataForm['total'] = $buscaPreco * $dataForm['quantidade']; 
        
                //altera os itens
                $update = $pedido->update($dataForm);
        
                    //verifica se foi alterado
                    if($update)
                    {
                        return redirect()->route('pedidos.index');
                    }
                    else 
                        return redirect()->route('pedidos.edit',$id)->with(['errors'=>'Falha ao editar']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
                $pedido = $this->pedido->find($id);
        
                $delete =  $pedido->delete();
        
                if($delete)
                {
                    return redirect()->route('pedidos.index');
                }
                else return redirect()->route('pedidos.show', $id)->with(['errors'=>'Falha ao deletar']);
    }

    public function teste(Pedido $requestss)
    {   
                dd($dataForm = $request->all());        

                $pedido = $this->pedido->find($id);
        
                return redirect()->route('pedidos.index');
    }

}

app/Http/Controllers/Painel/UserController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/painel/pedidos/create-edit.blade.php
@extends('adminlte::page')

@section('content')


    <div class="row">
        
    
    
    {!! Form::open(['route'=>'pedidos.store', 'class'=>'form']) !!}
    
    <td>{!! Form::select('cliente_id', $plucked, null,['class'=>'form-control']) !!}</td>
    
    
    {!! Form::select('produto_id', $produtos, null,['class'=>'form-control','id'=> 'produto' ]) !!}
    
    {!! Form::number('produto_qtde',  0,['class'=>'form-control','id'=> 'produto_qtde']) !!}
    {!! Form::text('produto_preco', null,['class'=>'form-control','id'=> 'produto_preco']) !!}

    <div class="modal-body">
            <div class="col-sm-6">
                </div>
                <div style="right: 7%" align="right" class="col-sm-6">
                    <a type="button" class="btn btn-success" onclick="adicionaLinha()">Add</a>
                </div>
                {!! Form::submit('Salvar', ['class'=>'btn-primary']) !!}
                {!! Form::close() !!}

        <table  class="table table-striped table-hover dataTables" id="tbgrade" >
            <thead>
            <tr>
                <th align="center">Produto</th>
                <th align="center">Quantidade</th>
                <th align="center">Preço Unitario</th>
                <th align="center">Sub Total</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                    <tr class="item">
     
    
                    </tr>      
            </tbody>
        </table>
       
    </div>
    
</div>

@endsection


<script>
             //Funcao para adicionar uma nova linha na tabela
             function adicionaLinha() {
                var newRow = $("<tr>");
                var Qtd = $("#produto_qtde").val();
                var Unitario = $("#produto_preco").val();
                var SubT = Qtd*Unitario;
                var cols = 
                
                '<td contenteditable="true"><input type="text" class="disabled no-border hidden" name="produto_id[]" value="' + $("#produto").val() + '"/>' + $("#produto option:selected").text() + '</td>' +
                '<td contenteditable="true"><input type="text" class="disabled no-border" name="Quantidade[]" value="' + $("#produto_qtde").val() + '"/></td>' +
                '<td contenteditable="true"><input type="text" class="disabled no-border" name="Preco[]" value="' + $("#produto_preco").val() + '"/></td>' +
                '<td contenteditable="true"><input type="text" class="disabled no-border" name="SubTotal[]" value=" ' + SubT + ' "/></td>' +
                '<td><button type="button" class="btn btn-danger" data-delete="endereco" onclick="remove(this)">Excluir</button></td>';
                
                
                newRow.append(cols);
                $('#tbgrade').find('tbody').append(newRow);}
            
</script>

resources/views/painel/pedidos/index.blade.php
@extends('adminlte::page') <!-- Puxando layout do adminLte -->


@section('content')

<h1 class="title-pg">Listagem de pedidos</h1>


<a href="{{route('pedidos.create')}}" class="btn btn-primary btn-add"> <!-- route( redireciona ao apertar o botao para a rota indicada) -->
    <span class="glyphicon glyphicon-plus"></span> Cadastrar
</a>

<table class="table table-striped">
<thead>
    <tr>
        <th>Cliente</th>
        <th>Email</th>    
        <th width = "100px">Ações</th>
    </tr>
    
</thead>
        <tr>
    @foreach ($pedidos as $pedido)

            <td>{{$pedido->cliente->name}}</td>
            <td>{{$pedido->cliente->email}}</td>
            
            
            <td>
                <a href="{{route('pedidos.edit', $pedido->id)}}" class="actions edit"> <!-- Apontando para rota edit -->
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                
                <a href="{{route('pedidos.show', $pedido->id)}}" class="actions delete">
                    <span class="glyphicon glyphicon-eye-open"></span>
                </a>

                {{--<a href="{{route('pedidos.destroy', $pedido->id)}}" class="actions delete">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>--}}
            </td>    
        </tr>

     
    @endforeach

</table>

{!! $pedidos->links()!!}

@endsection

resources/views/painel/pedidos/show.blade.php
@extends('adminlte::page')

@php
$total2 =0;
@endphp

@section('content')

<h1 class="title-pg">
    <a href="{{route('pedidos.index')}}"><span class="glyphicon glyphicon-fast-backward"></span></a>
    Itens
</h1>


@if(isset($errors) && count($errors)>0)

    <div class= "alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{$error}}</p>
        @endforeach
    </div>
@endif


<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>  
            <th>Quantidade</th>
            <th>Sub Total</th> 
            <th>Ação</th>  
            <th width = "150px">Total</th>
        </tr>
    </thead> 

    @if(isset($carrinhos)) 
        @foreach ($carrinhos as $carrinho)
            <tr>
                <td>{{$carrinho->product->name}}</td>
                <td>{{$carrinho->quantidade}}</td>
                <td>{{$carrinho->sub_total}}</td>
                
                @php
                $total2 += $carrinho->sub_total
                @endphp
                <td>
                        {{--<a href="{{route('pedidos.index')}}" class="actions edit"> <!-- Apontando para rota edit -->
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a> --}}
                        
                        {!! Form::open(['route'=>['carrinho.destroy',$carrinho->id],'method'=>'DELETE']) !!}
                        
                        {!! Form::submit("Excluir", ['class' =>'btn btn-danger']) !!}
                        
                        
                        {!! Form::close() !!}
                    </td>    
            </tr>
            
        @endforeach 
        <td></td> 
        <td></td> 
        <td></td>
        <td></td>  
        <td><b>{{$total ?? $total2}}</b></td>      
    @endif

@endsection